# Use this file with Vagrant to set up the Docker environment

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    networks:
      - app-network
    environment:
      POSTGRES_DB: student_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app1:
    build: .
    container_name: student_api_1
    networks:
      - app-network
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: student_db
      DB_SSL_MODE: disable
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  app2:
    build: .
    container_name: student_api_2
    networks:
      - app-network
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: student_db
      DB_SSL_MODE: disable
      SERVER_PORT: 8080
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    networks:
      - app-network
    ports:
      - "8080:80"
    volumes:
      - ./vagrant/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge