# This file is for reference only
# The actual secret will be created by External Secrets Operator
# from HashiCorp Vault

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: student-api
type: Opaque
# Data will be populated by ESO from Vault:
# DB_USER: <from vault>
# DB_PASSWORD: <from vault>