{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.vault.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  provider:
    vault:
      server: "http://{{ .Values.vault.name }}-service.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.vault.service.port }}"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
{{- end }}