apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.vault.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Values.vault.name }}
  ports:
  - port: {{ .Values.vault.service.port }}
    targetPort: {{ .Values.vault.service.port }}
    protocol: TCP
  type: {{ .Values.vault.service.type }}