apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.vault.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  token: {{ .Values.vault.dev.rootToken | b64enc }}