apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  labels:
    app: student-api
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
        tier: application
    spec:
      nodeSelector:
        type: application
      containers:
      - name: student-api
        image: bournemouth-uni-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "student_db"
        - name: DB_SSL_MODE
          value: "disable"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  labels:
    app: student-api
spec:
  selector:
    app: student-api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: student-api-nodeport
  labels:
    app: student-api
spec:
  selector:
    app: student-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  type: NodePort