apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretstores.external-secrets.io
spec:
  group: external-secrets.io
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              provider:
                type: object
                x-kubernetes-preserve-unknown-fields: true
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: secretstores
    singular: secretstore
    kind: SecretStore
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.external-secrets.io
spec:
  group: external-secrets.io
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              refreshInterval:
                type: string
              secretStoreRef:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              target:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              data:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: externalsecrets
    singular: externalsecret
    kind: ExternalSecret