apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: student-api
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "student_db"
  DB_SSL_MODE: "disable"
  SERVER_PORT: "8080"