apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
  labels:
    app: student-api
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
        tier: application
    spec:
      initContainers:
      - name: migration
        image: tenifuzy01/v1:latest
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for database to be ready..."
          until nc -z $DB_HOST $DB_PORT; do
            echo "Waiting for PostgreSQL at $DB_HOST:$DB_PORT..."
            sleep 2
          done
          echo "Database is ready, running migrations..."
          /app/main migrate || echo "Migration completed or no changes needed"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      containers:
      - name: student-api
        image: tenifuzy01/v1:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  namespace: student-api
  labels:
    app: student-api
spec:
  selector:
    app: student-api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: student-api-loadbalancer
  namespace: student-api
  labels:
    app: student-api
spec:
  selector:
    app: student-api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer