apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.postgresql.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.database.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.database.password | b64enc }}